// Test case that compares a file generated by rust_xlsxwriter with a file
// created by Excel.
//
// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Copyright 2022-2026, John McNamara, jmcnamara@cpan.org

use crate::common;
use rust_xlsxwriter::{
    Format, PivotTable, PivotTableDataField, PivotTableFunction, PivotTableStyle, Workbook,
    Worksheet, XlsxError,
};

// Write the pivot table source data.
fn write_source_data(worksheet: &mut Worksheet) -> Result<(), XlsxError> {
    worksheet.set_column_width(0, 12)?;
    worksheet.set_column_width(1, 12)?;
    worksheet.set_column_width(2, 12)?;
    worksheet.set_column_width(3, 12)?;

    let header_format = Format::new().set_bold();
    worksheet.write_string_with_format(0, 0, "Region", &header_format)?;
    worksheet.write_string_with_format(0, 1, "Item", &header_format)?;
    worksheet.write_string_with_format(0, 2, "Volume", &header_format)?;
    worksheet.write_string_with_format(0, 3, "Month", &header_format)?;

    let data = common::get_pivot_table_data();
    for (row, data) in data.iter().enumerate() {
        let row = 1 + row as u32;
        worksheet.write_string(row, 0, data.0)?;
        worksheet.write_string(row, 1, data.1)?;
        worksheet.write_number(row, 2, data.2)?;
        worksheet.write_string(row, 3, data.3)?;
    }

    Ok(())
}

// Test several pivot tables that share one pivot cache.
fn create_new_xlsx_file(filename: &str) -> Result<(), XlsxError> {
    let mut workbook = Workbook::new();

    let worksheet = workbook.add_worksheet().set_name("Data")?;
    write_source_data(worksheet)?;

    let pivot_table1 = PivotTable::new()
        .set_name("VolumeByRegion")
        .set_data_source(("Data", 0, 0, 50, 3))
        .add_row_field("Region")
        .add_data_field(PivotTableDataField::new("Volume"));

    let pivot_table2 = PivotTable::new()
        .set_name("VolumeByItem")
        .set_data_source(("Data", 0, 0, 50, 3))
        .set_style(PivotTableStyle::Medium9)
        .add_row_field("Item")
        .add_column_field("Month")
        .add_data_field(PivotTableDataField::new("Volume"));

    let pivot_table3 = PivotTable::new()
        .set_name("AverageVolumeByRegion")
        .set_data_source(("Data", 0, 0, 50, 3))
        .set_style(PivotTableStyle::Dark1)
        .add_row_field("Region")
        .add_data_field(
            PivotTableDataField::new("Volume")
                .set_function(PivotTableFunction::Average)
                .set_name("Average Volume"),
        );

    let worksheet = workbook.add_worksheet().set_name("Volume by Region")?;
    worksheet.add_pivot_table(0, 0, &pivot_table1)?;

    let worksheet = workbook.add_worksheet().set_name("Volume by Item")?;
    worksheet.add_pivot_table(0, 0, &pivot_table2)?;
    worksheet.add_pivot_table(10, 0, &pivot_table3)?;

    workbook.save(filename)?;

    Ok(())
}

#[test]
fn test_pivot_table02() {
    let test_runner = common::TestRunner::new()
        .set_name("pivot_table02")
        .set_function(create_new_xlsx_file)
        .initialize();

    test_runner.assert_eq();
    test_runner.cleanup();
}
