// Test case that compares a file generated by rust_xlsxwriter with a reference
// file.
//
// The reference file was generated by rust_xlsxwriter and not by Excel: Excel
// recreates the pivot cache and the extent of a pivot table when it opens a
// file, so it cannot save a file in this state.
//
// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Copyright 2022-2026, John McNamara, jmcnamara@cpan.org

use crate::common;
use rust_xlsxwriter::{
    ExcelDateTime, Format, PivotTable, PivotTableDataField, PivotTableLayout, Workbook, Worksheet,
    XlsxError,
};

// Write the pivot table source data. The "Region" column has a blank cell and
// the "Date" column holds dates, so that the field values of the pivot cache
// cover the string, number and blank cases.
fn write_source_data(worksheet: &mut Worksheet) -> Result<(), XlsxError> {
    let header_format = Format::new().set_bold();
    let date_format = Format::new().set_num_format("dd/mm/yyyy");

    worksheet.write_string_with_format(0, 0, "Region", &header_format)?;
    worksheet.write_string_with_format(0, 1, "Date", &header_format)?;
    worksheet.write_string_with_format(0, 2, "Volume", &header_format)?;

    worksheet.write_string(1, 0, "East")?;
    worksheet.write_string(2, 0, "West")?;
    worksheet.write_string(4, 0, "East")?;

    let dates = [(2026, 1, 15), (2026, 2, 20), (2026, 1, 15), (2026, 3, 10)];
    for (row, (year, month, day)) in dates.iter().enumerate() {
        let date = ExcelDateTime::from_ymd(*year, *month, *day)?;
        worksheet.write_datetime_with_format(1 + row as u32, 1, &date, &date_format)?;
    }

    worksheet.write_column(1, 2, [9000, 5000, 7000, 3000])?;

    Ok(())
}

// Test the default pivot table output for a row field without subtotals, which
// doesn't get the default item that stands for the subtotal.
fn create_new_xlsx_file(filename: &str) -> Result<(), XlsxError> {
    let mut workbook = Workbook::new();

    let worksheet = workbook.add_worksheet().set_name("Data")?;
    write_source_data(worksheet)?;

    let pivot_table = PivotTable::new()
        .set_data_source(("Data", 0, 0, 4, 2))
        .set_layout(PivotTableLayout::Tabular)
        .add_row_field("Region")
        .add_row_field("Date")
        .set_show_field_subtotals("Date", false)
        .add_data_field(PivotTableDataField::new("Volume"));

    let worksheet = workbook.add_worksheet().set_name("Pivot")?;
    worksheet.add_pivot_table(0, 0, &pivot_table)?;

    workbook.save(filename)?;

    Ok(())
}

#[test]
fn test_pivot_table04() {
    let test_runner = common::TestRunner::new()
        .set_name("pivot_table04")
        .set_function(create_new_xlsx_file)
        .initialize();

    test_runner.assert_eq();
    test_runner.cleanup();
}
